// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  hooks: {
    'prerender:routes'({ routes }) {
      // Routes are generated by default for SSG
    }
  }
})
